Repository TecArt/TecArt-Ticket-System, pull requests merged in 2020-10, with the labels that each got.

#40 Issue#8 vi + correct en mistake
  lang/en.php
  lang/vi.php
Labels: Hacktoberfest, Hacktoberfest-accepted

#38 Added Dutch (nl) language for TecArt Ticket System
  lang/nl.php
Labels: translation

#36 Add Romanian language
  lang/ro.php
Labels: translation

#33 add translation to id
  lang/id.php
Labels: duplicate, translation

#17 Add Russian translation
  lang/ru.php
Labels: translation
